### ISSUE TITLE
A classic age-old Array problem

### ISSUE THREAD

**Issue by geraldchecka** [bhargav175/fizzbuzz#1]
Hey! I have a question.
When you say Array.apply(null, {length: n}), it creates array of length 'n' with values as undefined. Are its values mapped to 0 or really undefined? Modern compilers internally initialize it to 0 if there is no value but when length is defined. This relates to Sparse Array&Dense Array problem. Do you know if V8/Spider Monkey/Chakra have this problem?

**Comment by imbhargav5** [comment]
Its dense array. Check this out! http://www.2ality.com/2012/06/dense-arrays.html. Chrome, Safari and Firefox give the same result. 

```
new Array(3) //empty array

Array.apply(null,{length:3}) //array initialised with undefined.
```
